-- liquibase formatted sql

-- changeset mprokhorova:1
CREATE TABLE recommendations (
    id BIGINT generated by default as identity primary key,
    product_name TEXT not null,
    product_id TEXT not null,
    product_text TEXT not null
)

-- changeset mprokhorova:2
CREATE TABLE rules (
    id BIGINT generated by default as identity primary key,
    query TEXT not null,
    arguments TEXT not null,
    negate boolean not null
)