-- liquibase formatted sql

-- changeset mprokhorova:1
CREATE TABLE queries (
    id BIGINT generated by default as identity primary key,
    query TEXT,
    arguments varchar,
    negate boolean,
    recommendations_id BIGINT
);

CREATE TABLE recommendations (
    id BIGINT generated by default as identity primary key,
    product_id UUID,
    product_name TEXT,
    product_text TEXT
);